### PR TITLE
Adds required parameter when numprocs > 1

### PR DESCRIPTION
**Pull request by tim-massey**
Sorry, I didnt add this before. I've tested this on various Ubuntu's now.

### CODE REVIEW

**Comment by seocam** [comment]
uhn... not sure if the process number it's a good name. 
What about use `<app_name>_<process_number>` ?

**Comment by tim-massey** [comment]
I did have that originally but supervisor doubled up. This is what it ends up looking like:

supervisor

**Comment by seocam** [comment]
Ack

**Comment by seocam** [comment]
New version released!

**Pull request merged**
